package project.euler

import org.junit.*

class Problem_02Test {

  /*
  Each new term in the Fibonacci sequence is generated by adding 
  the previous two terms. By starting with 1 and 2, the first 
  10 terms will be:
  
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values 
  do not exceed four million, find the sum of the even-valued terms.
  */

  @Test
  void should_generate_fibonacci_sequence() {
    assert new Problem_02().getFibonacciSeries(0)    == [0, 1]
    assert new Problem_02().getFibonacciSeries(6)    == [0, 1, 1, 2, 3, 5]
    assert new Problem_02().getFibonacciSeries(13)   == [0, 1, 1, 2, 3, 5, 8, 13]
    assert new Problem_02().getFibonacciSeries(100)  == [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
  }

  @Test
  void should_only_add_even_valued_terms() {
    assert new Problem_02().addEvenTerms([0,1]) == 0
    assert new Problem_02().addEvenTerms([0,1,1,2,3,5,8,13]) == 10
    assert new Problem_02().addEvenTerms([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]) == 44
  }
}
